blog/__init__.py
from flask import Blueprint

PREFIX = "blog/"
blog_bp = Blueprint(
	'blog', __name__,
	template_folder='templates',
	static_folder='static',
	url_prefix='/blog'
)

import blog.views

blog/views.py
import os
import sys
import traceback
from collections import Counter

from pygments.formatters.html import HtmlFormatter
from werkzeug.exceptions import HTTPException

from main import *
from . import *


@blog_bp.errorhandler(Exception)
def handle_exception(e):
	if isinstance(e, HTTPException):
		return render_template("main/404.html"), e.code


@blog_bp.route("/")
def index():
	# app.config["FLATPAGES_ROOT"] = os.path.join(app.root_path, "posts")
	# flatpages.reload()
	app.logger.debug("flatpages_root = %s", app.config["FLATPAGES_ROOT"])
	app.logger.debug("flatpages = %s", [p.path for p in flatpages])
	try:
		_posts = get_all_posts(PREFIX)
		return render_template("blog/index.html", posts=_posts)
	except Exception:
		traceback.print_exc()


@blog_bp.route("/posts/<postname>")
def show_post(postname):
	post = flatpages.get_or_404(PREFIX + postname)
	return render_template("blog/post.html", post=post)


@blog_bp.route("/posts")
def posts():
	_posts = get_all_posts(PREFIX)
	return render_template("blog/posts.html", posts=_posts)


@blog_bp.route("/categories")
def categories():
	_posts = get_all_posts(PREFIX)
	categories_counter = Counter(p["category"] for p in _posts)
	return render_template(
		"blog/listing.html", metadata_type="categories", metadata_listing=sorted(categories_counter.items())
	)


@blog_bp.route("/categories/<name>")
def show_posts_with_category(name):
	_posts = get_all_posts(PREFIX)
	return render_template("blog/posts.html", posts=_posts, filter_category=name)


@blog_bp.route("/tags")
def tags():
	_posts = get_all_posts(PREFIX)
	tags_counter = Counter(tag for p in _posts for tag in p["tags"])
	return render_template(
		"blog/listing.html", metadata_type="tags", metadata_listing=sorted(tags_counter.items())
	)


@blog_bp.route("/tags/<name>")
def show_posts_with_tag(name):
	_posts = get_all_posts(PREFIX)
	return render_template("blog/posts.html", posts=_posts, filter_tag=name)


@blog_bp.route("/search", methods=["GET", "POST"])
def search():
	# from forms import SearchForm
	# search_form = SearchForm()

	if request.method == "GET":
		query = request.args.get("s")
		results = []
		_posts = get_all_posts(PREFIX)
		for post in _posts:
			# TODO: Elastic search
			if post["category"].find(query) != -1 or any(tag.find(query) != -1 for tag in post["tags"])\
				or post["title"].find(query) != -1:
				results.append(post)

		return render_template("blog/results.html", query=query, results=results)

blog/templates/blog/core.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{{ title }} - {{ site_title }}</title>
		<link rel="icon" href="{{ url_for('.static', filename='image/favicon.ico') }}" type="image/x-icon">
		<script id="dsq-count-scr" src="//{{ site_disqus }}.disqus.com/count.js" async></script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous">
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous"></script>
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/v4-shims.css">
		<script src="https://twemoji.maxcdn.com/v/latest/twemoji.min.js" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="{{ url_for('.static', filename='css/core.css') }}">
		<link rel="stylesheet" href="{{ url_for('.static', filename='css/markdown.css') }}">
		<script type="text/javascript" src="{{ url_for('.static', filename='js/emoji_unicode.json') }}"></script>
		<script type="text/javascript" src="{{ url_for('.static', filename='js/emoji.js') }}"></script>
		{% block head_extension %}
		{% endblock %}
	</head>
	<body>
		<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
			<a class="navbar-brand" href="{{ url_for('.index') }}"><i class="fa fa-code"></i> {{ site_title }}</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('blog.posts') }}">Posts</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('.categories') }}">Categories</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('.tags') }}">Tags</a>
					</li>
				</ul>
				<form class="form-inline" action="{{ url_for('.search') }}">
					<input class="form-control" type="search" placeholder="Search..." name="s" required>
					<button class="btn btn-outline-primary search_btn" type="submit"><i class="fa fa-search"></i></button>
				</form>
			</div>
		</nav>
		<div class="container">
			{% block container %}
			{% endblock container %}
		</div>
		<footer class="footer">
			<div class="container">
				<p>Copyright © 2022{# site_now.year #}. Make with <i class="fa fa-heart"></i> by <a href="https://github.com/{{ site_github }}">@{{ site_github }}</a>.</p>
				{# <div><a href="https://github.com/{{ site_github }}"><i class="fa fa-github fa-3x"></i></a></div> #}
			</div>
		</footer>
		<script>convert_emoji();</script>
	</body>
</html>

blog/templates/blog/index.html
{% extends "blog/core.html" %}

{% set title = "Home page" %}

{% block container %}
	<h1>Hello!</h1>
	<h2>Recent posts</h2>

	{% from 'blog/posts.html' import create_posts_list %}
	{{ create_posts_list(posts) }}
{% endblock container %}

blog/templates/blog/listing.html
{% extends "blog/core.html" %}

{#
	listing.html is a merged version of categories.html and tags.html
	metadata_type in ["categories", "tags"]
#}

{% set title = metadata_type.capitalize() %}
{% block head_extension %}
	<link rel="stylesheet" href="{{ url_for('.static', filename='css/listing.css') }}">
{% endblock %}

{% block container %}
	<h3>All {{ metadata_type }}</h3>

	<div class="listing_div">
	{% for name, posts_count in metadata_listing %}
		<div class="badge_listing_col">
			{% set badge_color_style = "btn-" + ("success" if metadata_type == "categories" else "secondary") %}

			<a class="btn {{ badge_color_style }} tag_badge" href="{{ url_for("."+metadata_type) }}/{{ name }}" role="button">
				{% if metadata_type == "categories" %}
					<i class="fa fa-code-fork"></i> 
				{% endif %}
				{{ name }}
			</a>
			<span>x {{ posts_count }}</span>
		</div>
	{% endfor %}
	</div>
{% endblock container %}

blog/templates/blog/post.html
{% extends "blog/core.html" %}

{% set title = post.title %}
{% block head_extension %}
	<link rel="stylesheet" href="{{ url_for('pygments_css') }}">
	<link rel="stylesheet" href="{{ url_for('.static', filename='css/codehilite.css') }}">
	<link rel="stylesheet" href="{{ url_for('.static', filename='css/post.css') }}">
	<script type="text/javascript" src="{{ url_for('.static', filename='js/post.js') }}"></script>
	<script type="text/javascript" id="MathJax-script" async
	        src="https://cdn.jsdelivr.net/npm/mathjax@3.0.0/es5/tex-mml-chtml.js"></script>
{% endblock %}

{% block container %}
	<div class="post_info">
		<div class="post_heading">
			<span class="_h1">{{ post.title }}</span> {# fake h1 #}
			{% if post.pinned is sameas true %}
				<span class="badge badge-primary pinned_badge" style="vertical-align: middle;"><i class="fa fa-thumb-tack"></i></span>
			{% endif %}
		</div>
		{% from 'blog/posts.html' import create_post_subtitle %}
		{{ create_post_subtitle(post, false) }}
	</div>
	<div class="post_body">
		<div id="post_left_side" class="left_side">
			<hr>
			{{ post.html|safe }}
		</div>
		<div id="post_right_side" class="right_side">
			<div id="toc"></div>
		</div>
		<div id="comment" class="left_side">
			<hr>
			<div id="disqus_thread"></div>
		</div>
		<script>
			create_toc();
			embed_disqus();
		</script>
		<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
	</div>
{% endblock container %}

blog/templates/blog/posts.html
{% extends "blog/core.html" %}

{% set description = "All posts" %}
{% if filter_category %}
	{% set description = description + " with category [%s]" % filter_category %}
{% endif %}

{% if filter_tag %}
	{% set description = description + " with tag #" + filter_tag %}
{% endif %}

{% set title = description %}
{% block head_extension %}
	<link rel="stylesheet" href="{{ url_for('.static', filename='css/post.css') }}">
{% endblock %}

{% macro create_post_subtitle(post, prefix, is_new_page_redirecting) %}
<div class="subtitle">
	<i class="fa fa-calendar"></i>
	<span> {{ post.date }}</span>
	<i class="fas fa-comment-alt"></i>
	{% set next_url = (url_for('.posts') + "/" + post.path[prefix|length:]) if is_new_page_redirecting is sameas true else "" %}
	<span><a href="{{ next_url }}#disqus_thread" class="comment_href"></a></span>
</div>
<div>
	<a class="btn btn-success tag_badge" href="{{ url_for('.categories') }}/{{ post.category }}" role="button">
		<i class="fa fa-code-fork"></i> {{ post.category }}
	</a>
	{% for tag in post.tags %}
	<a class="btn btn-secondary tag_badge" href="{{ url_for('.tags') }}/{{ tag }}" role="button">{{ tag }}</a>
	{% endfor %}
</div>
{% endmacro %}

{% macro create_posts_list(posts, filter_category=None, filter_tag=None) %}
	{% set prefix = "blog/" %}
	<ul class="list-group">
	{% for post in posts %}
		{% if (not filter_category or filter_category == post.category) and (not filter_tag or filter_tag in post.tags) %}
		<li class="list-group-item post_info">
			<span>
				{% if post.pinned is sameas true %}
					<span class="badge badge-primary pinned_badge"><i class="fa fa-thumb-tack"></i></span>
				{% endif %}
				<a class="listing_post_title" href="{{ url_for('.posts') }}/{{ post.path[prefix|length:] }}">{{ post.title }}</a>
			</span>
			{{ create_post_subtitle(post, prefix, true) }}
		</li>
		{% endif %}
	{% endfor %}
	</ul>
{% endmacro %}

{% block container %}
<h3>{{ description }}</h3>
{{ create_posts_list(posts, filter_category, filter_tag) }}
{% endblock container %}

blog/templates/blog/results.html
{% extends "blog/core.html" %}

{% set title = "Search results for " + query %}

{% block container %}
	{% if results %}
		<h3>Search results for `{{ query }}`</h3>
		{#
		<hr>
		<h4>Categories</h4>
		<hr>
		<h4>Tags</h4>
		<hr>
		<h4>Posts</h4>
		#}
		{% from 'blog/posts.html' import create_posts_list %}
		{{ create_posts_list(results) }}
	{% else %}
		<h3>No results found for `{{ query }}`!</h3>
	{% endif %}
{% endblock container %}

blog/templates/index.html
{% extends "core.html" %}

{% set title = "Home page" %}

{% block container %}
	<h1>Hello!</h1>
	<h2>Recent posts</h2>

	{% from 'posts.html' import create_posts_list %}
	{{ create_posts_list(posts) }}
{% endblock container %}

blog/templates/post.html
{% extends "core.html" %}

{% set title = post.title %}
{% block head_extension %}
	<link rel="stylesheet" href="{{ url_for('.pygments_css') }}">
	<link rel="stylesheet" href="{{ url_for('.static', filename='css/codehilite.css') }}">
	<link rel="stylesheet" href="{{ url_for('.static', filename='css/post.css') }}">
	<script type="text/javascript" src="{{ url_for('.static', filename='js/post.js') }}"></script>
	<script type="text/javascript" id="MathJax-script" async
	        src="https://cdn.jsdelivr.net/npm/mathjax@3.0.0/es5/tex-mml-chtml.js"></script>
{% endblock %}

{% block container %}
	<div class="post_info">
		<div class="post_heading">
			<span class="_h1">{{ post.title }}</span> {# fake h1 #}
			{% if post.pinned is sameas true %}
				<span class="badge badge-primary pinned_badge" style="vertical-align: middle;"><i class="fa fa-thumb-tack"></i></span>
			{% endif %}
		</div>
		{% from 'posts.html' import create_post_subtitle %}
		{{ create_post_subtitle(post, false) }}
	</div>
	<div class="post_body">
		<div id="post_left_side" class="left_side">
			<hr>
			{{ post.html|safe }}
		</div>
		<div id="post_right_side" class="right_side">
			<div id="toc"></div>
		</div>
		<div id="comment" class="left_side">
			<div id="disqus_thread"></div>
		</div>
		<script>
			create_toc();
			embed_disqus();
		</script>
		<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
	</div>
{% endblock container %}

blog/templates/posts.html
{% extends "core.html" %}

{% set description = "All posts" %}
{% if filter_category %}
	{% set description = description + " with category [%s]" % filter_category %}
{% endif %}

{% if filter_tag %}
	{% set description = description + " with tag #" + filter_tag %}
{% endif %}

{% set title = description %}
{% block head_extension %}
	<link rel="stylesheet" href="{{ url_for('.static', filename='css/post.css') }}">
{% endblock %}

{% macro create_post_subtitle(post, is_new_page_redirecting) %}
<div class="subtitle">
	<i class="fa fa-calendar"></i>
	<span> {{ post.date }}</span>
	<i class="fas fa-comment-alt"></i>
	{% set next_url = (url_for('.posts') + "/" + post.path) if is_new_page_redirecting is sameas true else "" %}
	<span><a href="{{ next_url }}#disqus_thread" class="comment_href"></a></span>
</div>
<div>
	<a class="btn btn-success tag_badge" href="{{ url_for('.categories') }}/{{ post.category }}" role="button">
		<i class="fa fa-code-fork"></i> {{ post.category }}
	</a>
	{% for tag in post.tags %}
		<a class="btn btn-secondary tag_badge" href="{{ url_for('.tags') }}/{{ tag }}" role="button">{{ tag }}</a>
	{% endfor %}
</div>
{% endmacro %}

{% macro create_posts_list(posts, filter_category=None, filter_tag=None) %}
<ul class="list-group">
{% for post in posts %}
	{% if (not filter_category or filter_category == post.category) and (not filter_tag or filter_tag in post.tags) %}
		<li class="list-group-item post_info">
			<span>
				{% if post.pinned is sameas true %}
					<span class="badge badge-primary pinned_badge"><i class="fa fa-thumb-tack"></i></span>
				{% endif %}
				<a class="listing_post_title" href="{{ url_for('.posts') }}/{{ post.path }}">{{ post.title }}</a>
			</span>
			{{ create_post_subtitle(post, true) }}
		</li>
	{% endif %}
{% endfor %}
</ul>
{% endmacro %}

{% block container %}
<h3>{{ description }}</h3>
{{ create_posts_list(posts, filter_category, filter_tag) }}
{% endblock container %}

blog/templates/results.html
{% extends "core.html" %}

{% set title = "Search results for " + query %}

{% block container %}
	{% if results %}
		<h3>Search results for `{{ query }}`</h3>
		{#
		<hr>
		<h4>Categories</h4>
		<hr>
		<h4>Tags</h4>
		<hr>
		<h4>Posts</h4>
		#}
		{% from 'posts.html' import create_posts_list %}
		{{ create_posts_list(results) }}
	{% else %}
		<h3>No results found for `{{ query }}`!</h3>
	{% endif %}
{% endblock container %}